language: ruby
rvm:
  - 2.3.0 
addons:
  firefox: latest
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  code_climate:
      repo_token: eeb02ac9ba9286992ab88a1dac58986684463093e8bf867893126c9157d9dad1